# K-MEANS CLUSTERING

In [10]:
#IMPORTING LIBRARY
import cv2
import numpy as np

In [11]:
#READING IMAGE
img=cv2.imread("C:/Users/SN149/Desktop/messi.webp")
img

array([[[31, 31, 31],
        [22, 22, 22],
        [16, 16, 16],
        ...,
        [14, 14, 14],
        [20, 20, 20],
        [33, 33, 33]],

       [[16, 16, 16],
        [ 7,  7,  7],
        [ 1,  1,  1],
        ...,
        [ 0,  0,  0],
        [ 6,  6,  6],
        [19, 19, 19]],

       [[10, 10, 10],
        [ 1,  1,  1],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [12, 12, 12]],

       ...,

       [[20, 20, 20],
        [ 0,  0,  0],
        [ 1,  1,  1],
        ...,
        [ 1,  1,  1],
        [ 0,  0,  0],
        [16, 16, 16]],

       [[20, 20, 20],
        [ 0,  0,  0],
        [ 1,  1,  1],
        ...,
        [ 1,  1,  1],
        [ 0,  0,  0],
        [16, 16, 16]],

       [[20, 20, 20],
        [ 0,  0,  0],
        [ 1,  1,  1],
        ...,
        [ 1,  1,  1],
        [ 0,  0,  0],
        [16, 16, 16]]], dtype=uint8)

In [12]:
#RGB CONVERSION
imgrgb=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

In [13]:
#RESHAPE
vec=imgrgb.reshape((-1,3))
vec

array([[31, 31, 31],
       [22, 22, 22],
       [16, 16, 16],
       ...,
       [ 1,  1,  1],
       [ 0,  0,  0],
       [16, 16, 16]], dtype=uint8)

In [14]:
#fLOAT CONVERSION
vec=np.float32(vec)
vec

array([[31., 31., 31.],
       [22., 22., 22.],
       [16., 16., 16.],
       ...,
       [ 1.,  1.,  1.],
       [ 0.,  0.,  0.],
       [16., 16., 16.]], dtype=float32)

In [15]:
#ITERATION TERMINATION CRITERIA
criteria=(cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER,100,1)

In [16]:
#Cluster Condition
k=3
attempts=100

In [17]:
#K-Means Clustering
compactness,label,center=cv2.kmeans(vec,k,None,criteria,attempts,cv2.KMEANS_PP_CENTERS)
center


array([[ 83.518524 ,  54.181255 ,  62.893818 ],
       [  2.8678825,   2.7533762,   4.209498 ],
       [184.17123  , 173.30981  , 152.43759  ]], dtype=float32)

In [19]:
#Uint Conversion
center=np.uint8(center)
center

array([[ 83,  54,  62],
       [  2,   2,   4],
       [184, 173, 152]], dtype=uint8)

In [21]:
#flattening and Reshape
res=center[label.flatten()]
res_img=res.reshape((imgrgb.shape))
res_img

array([[[2, 2, 4],
        [2, 2, 4],
        [2, 2, 4],
        ...,
        [2, 2, 4],
        [2, 2, 4],
        [2, 2, 4]],

       [[2, 2, 4],
        [2, 2, 4],
        [2, 2, 4],
        ...,
        [2, 2, 4],
        [2, 2, 4],
        [2, 2, 4]],

       [[2, 2, 4],
        [2, 2, 4],
        [2, 2, 4],
        ...,
        [2, 2, 4],
        [2, 2, 4],
        [2, 2, 4]],

       ...,

       [[2, 2, 4],
        [2, 2, 4],
        [2, 2, 4],
        ...,
        [2, 2, 4],
        [2, 2, 4],
        [2, 2, 4]],

       [[2, 2, 4],
        [2, 2, 4],
        [2, 2, 4],
        ...,
        [2, 2, 4],
        [2, 2, 4],
        [2, 2, 4]],

       [[2, 2, 4],
        [2, 2, 4],
        [2, 2, 4],
        ...,
        [2, 2, 4],
        [2, 2, 4],
        [2, 2, 4]]], dtype=uint8)

In [24]:
#Original image & Cluster image
cv2.imshow('Original',img)
cv2.imshow('Segmented',res_img)

cv2.waitKey(0)
cv2.destroyAllWindows()